import { Gabarito } from 'next/font/google'
import "./globals.css";

const gabarito = Gabarito({ subsets: ['latin'] })


export const metadata = {
  title: "Library Book Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} bg-color-dark`} suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
